version: '3.8'

services:
  ms_ai:
    build: ./ms_ai
    ports:
      - "8001:8000"
    env_file:
      - .env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
